name: CI/CD - Build, Push & Update Manifests

on:
  push:
    branches:
      - main

env:
  IMAGE_REPO: vitoryuji25/hello-app

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_REPO }}:latest
            ${{ env.IMAGE_REPO }}:${{ github.sha }}

      - name: Configure SSH for manifests repo
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clone manifests repo and update image
        env:
          IMAGE_TAG: ${{ github.sha }}
          IMAGE_REPO: ${{ env.IMAGE_REPO }}
        run: |
          git clone git@github.com:VitorYuji25/hello-manifests.git manifests
          cd manifests
          # substitui a imagem no deployment.yaml (ajuste regex conforme seu yaml)
          sed -i "s|image: .*|image: ${IMAGE_REPO}:${IMAGE_TAG}|g" deployment.yaml
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git checkout -b update-image-${IMAGE_TAG}
          git add deployment.yaml
          git commit -m "ci: update image to ${IMAGE_TAG}"
          git push origin HEAD

      - name: Create PR in manifests repo (via GitHub API)
        if: ${{ secrets.MANIFESTS_GITHUB_TOKEN }}
        env:
          GITHUB_API_TOKEN: ${{ secrets.MANIFESTS_GITHUB_TOKEN }}
          BRANCH: update-image-${{ github.sha }}
        run: |
          cat > payload.json <<EOF
          {
            "title": "ci: update image ${{ github.sha }}",
            "head": "${BRANCH}",
            "base": "main",
            "body": "Automated image update from CI"
          }
          EOF
          curl -s -X POST -H "Authorization: token $GITHUB_API_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/your-org/hello-manifests/pulls \
            -d @payload.json
